# Generated by Django 4.2.1 on 2023-06-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='group_list',
            new_name='origin_groups',
        ),
    ]
