# Generated by Django 4.2.1 on 2023-06-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_group_list_customuser_origin_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='origin_groups',
            new_name='origin_group',
        ),
    ]
