# Generated by Django 4.2.1 on 2023-06-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_message_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.role'),
        ),
    ]
