# Generated by Django 4.2.1 on 2023-06-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updatedat_at',
            new_name='updated_at',
        ),
    ]
