[{'type': 'table', 'name': 'django_migrations', 'tbl_name': 'django_migrations', 'rootpage': 2, 'sql': 'CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL)'}, {'type': 'table', 'name': 'sqlite_sequence', 'tbl_name': 'sqlite_sequence', 'rootpage': 3, 'sql': 'CREATE TABLE 
sqlite_sequence(name,seq)'}, 
{'type': 'table', 'name': 'auth_group_permissions', 'tbl_name': 'auth_group_permissions', 'rootpage': 9, 'sql': 'CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED)'}, {'type': 'table', 'name': 'auth_user_groups', 'tbl_name': 'auth_user_groups', 'rootpage': 12, 'sql': 'CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED)'}, {'type': 'table', 'name': 'auth_user_user_permissions', 'tbl_name': 'auth_user_user_permissions', 'rootpage': 13, 'sql': 'CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES 
"auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE 
INITIALLY DEFERRED)'}, 
{'type': 'table', 'name': 'django_admin_log', 'tbl_name': 'django_admin_log', 'rootpage': 29, 'sql': 'CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0))'}, {'type': 'table', 'name': 'django_content_type', 'tbl_name': 'django_content_type', 'rootpage': 5, 'sql': 'CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL)'}, {'type': 'table', 'name': 'auth_permission', 'tbl_name': 'auth_permission', 'rootpage': 30, 'sql': 'CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT 
NULL, "name" varchar(255) NOT NULL)'},
 {'type': 'table', 'name': 'auth_group', 'tbl_name': 'auth_group',
  'rootpage': 15, 'sql': 'CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE)'}, 
  {'type': 'table', 'name': 'auth_user', 'tbl_name': 'auth_user', 'rootpage': 7, 'sql': 'CREATE TABLE "auth_user"
   ("id" integer NOT NULL 
   
   PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL)'}, {'type': 'table', 'name': 'books_book', 'tbl_name': 'books_book', 'rootpage': 10, 'sql': 'CREATE TABLE "books_book" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "author" varchar(200) NOT NULL, "title" varchar(200) NOT NULL, "is_special" bool NOT NULL)'}, {'type': 'table', 'name': 'books_publisher', 'tbl_name': 'books_publisher', 'rootpage': 11, 'sql': 'CREATE TABLE "books_publisher" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)'}, {'type': 'table', 'name': 'books_comment', 'tbl_name': 'books_comment', 'rootpage': 32, 'sql': 'CREATE TABLE "books_comment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "comment" varchar(200) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "book_id" integer NOT NULL REFERENCES "books_book" ("id") DEFERRABLE INITIALLY DEFERRED)'}, {'type': 'table', 'name': 'django_session', 'tbl_name': 'django_session', 'rootpage': 35, 'sql': 
'CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL)'}]
>>>
