[tool.black]
line-length = 120
target-version = ['py310']  # Pythonのバージョン
include = '\.py$'  # 対象ファイル
skip-string-normalization = true  # ''を""に変換しない設定(好みで変えてください)

# フォーマットしないファイル
exclude = '''
(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | venv
    | \.idea
    | \.vscode
    | _build
    | buck-out
    | build
    | dist
    | migrations
)
'''