# Generated by Django 5.0.6 on 2024-06-24 05:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='meta',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
