# Generated by Django 3.1 on 2021-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210428_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
