version: "3"
services:
  db:
      image: postgis/postgis:15-3.3
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'