# Generated by Django 4.2.1 on 2023-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_task_new_product_task_old_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_path", models.FilePathField()),
                ("feature_path", models.FilePathField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
