# Generated by Django 4.2.1 on 2023-11-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0004_fisicalyear"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FisicalYear",
            new_name="FiscalYear",
        ),
        migrations.CreateModel(
            name="AcqPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("1Q", "第一四半期"),
                            ("2Q", "第二四半期"),
                            ("3Q", "第三四半期"),
                            ("4Q", "第四四半期"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "fisical_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snippets.fiscalyear",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
