# Generated by Django 4.2.1 on 2023-11-13 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0005_rename_fisicalyear_fiscalyear_acqperiod"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acqperiod",
            old_name="fisical_year",
            new_name="fiscal_year",
        ),
    ]
