# Generated by Django 4.2.1 on 2023-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0006_rename_fisical_year_acqperiod_fiscal_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["-created_at"], name="snippets_ta_created_9613bc_idx"
            ),
        ),
    ]
